build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
codenotary:
  signer: your@email.com
  base_image: codenotary@home-assistant.io
args:
  BUILD_VERSION: 1.0.0
