# Home Assistant Add-on: Raspberry Pi LED Control
# Repository structure for the add-on

# addon/config.yaml
name: "Raspberry Pi LED Control"
version: "1.0.0"
slug: "disable_led"
description: "Control the LEDs on your Raspberry Pi (power and activity LEDs)"
url: "https://github.com/dyarfaradj/homeassistant-addons/tree/main/disable-led"
arch:
  - armhf
  - armv7
  - aarch64
startup: application
boot: auto
init: false
full_access: true
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
map:
  - config:rw
options:
  power_led: "on"
  activity_led: "on"
schema:
  power_led: list(on|off|heartbeat|mmc|timer)
  activity_led: list(on|off|heartbeat|mmc|timer)
