# Home Assistant Add-on: LG Dev Session Auto Renew
name: "LG Dev Session Auto Renew"
version: "1.0.3"
slug: "lg_dev_session"
description: "Automatically calls an LG Developer URL to renew Developer Mode sessions on your LG webOS TV"
url: "https://github.com/dyarfaradj/homeassistant-addons/tree/main/lg-dev-session"
arch:
  - armhf
  - armv7
  - aarch64
startup: application
boot: auto
init: false
map:
  - config:rw
options:
  url: "https://developer.lge.com/secure/ResetDevModeSession.dev?sessionToken=YOUR_TOKEN_HERE"
  interval_hours: 48
schema:
  url: str
  interval_hours: int(1,168)
